import { AddressChannel, AddressUsage, AvatarUsage, BoatType, BoatUsage, ColorIonic, CompetitionLevel, DeliveryType, GenderType, Importance, MemberType, ModelType, OrgType, Periodicity, PersonSortCriteria, Priority, ResourceType, RoleEnum, ScsMemberType, ViewPosition } from "@bk/categories";
import { NameDisplay } from "@bk/util";
import { SectionProperties } from "../section/section.model";
import { RelationshipProperties } from "../relationship/relationship.model";

// use i18n literals with '@input.NAME.label|placeholder|helper|error'
export type BkFormModel = Partial<{
  abbreviation: string,
  addressChannel: AddressChannel,   // address: category
  addressChannelIcon: string,      // address: url 
  addressChannelLabel: string,
  addressUsage: AddressUsage,
  addressUsageLabel: string,
  addressValue: string,     // address: name
  addressValue2: string,
  amount: number,           // invoicePosition: amount
  altText: string,
  area: string,
  assignee: string,
  authorName: string,     // comment: name
  authorAvatar: string,   // comment: url
  authorId: string,   
  avatarUrl: string,    // person/competitionLevel: url, 
  avatarUsage: AvatarUsage,
  bexioId: string,
  boatName: string,   
  boatType: BoatType,       // resource: subType
  boatUsage: BoatUsage,
  bkey: string,
  calendarName: string,
  category: number,
  city: string,
  confirmed: boolean,
  content: string,
  count: string,
  countryCode: string,
  color: ColorIonic,
  competitionLevel: CompetitionLevel, 
  creationDate: string,
  currency: string,
  currentValue: number,
  dateOfBirth: string,
  dateOfDeath: string,
  dateOfDocCreation: string,
  dateOfDocLastUpdate: string,
  dateOfEntry: string,
  dateOfExit: string,
  dateOfFoundation: string,
  dateOfLiquidation: string,
  description: string,
  dir: string,
  direction: number,
  dueDate: string,
  endDate: string,
  endTime: string,
  email: string,
  extension: string,
  fileName: string,
  firstName: string,
  function: string,
  gender: GenderType,   // person/competitionLevel: category
  gravatarEmail: string,
  height: number,
  hexColor: string,
  iban: string,
  icon: string,
  imagePosition: ViewPosition,
  importance: Importance,
  index: string,
  invoiceDelivery: DeliveryType,
  isBillable: boolean,
  isCc: boolean,
  isArchived: boolean,
  isFavorite: boolean,
  isTest: boolean,
  isValidated: boolean,
  keyName: string,
  keyNr: number,
  label: string,
  lastName: string,       // competitionModel: name
  latitude: number,
  load: string,
  longitude: number,
  locationKey: string,
  locations: string[],
  locationType: number,
  lockerNr: number,
  md5hash: string,
  membershipId: string,
  memberCategory: number,
  memberKey: string,
  memberState: number,
  memberUrl: string,
  menuAction: string,
  mimeType: string,
  modelType: ModelType,
  name: string,
  nameDisplay: NameDisplay,
  newsDelivery: DeliveryType,
  nickName: string,
  notes: string,
  objectCategory: number,
  objectKey: string,
  objectName: string,
  objectName2: string,
  objectType: ModelType,
  objectUrl: string,
  orgFunction: string,
  orgId: string,
  orgName: string,
  orgType: OrgType,
  orgUrl: string,
  participants: string,
  password: string,
  placeId: string,
  personKey: string,
  persons: string[],
  personSortCriteria: PersonSortCriteria,
  periodicity: Periodicity,
  phone: string,
  priority: Priority,
  priorVersionKey: string,
  price: number,
  reference: string,
  relationshipProperties: RelationshipProperties,
  relDate: string,
  repeatUntilDate: string,
  resourceKey: string,
  resourceType: ResourceType,
  roleNeeded: RoleEnum,
  scsMembershipKey: string,
  scsMemberType: ScsMemberType,
  showDebugInfo: boolean,
  showTestData: boolean,
  showArchivedData: boolean,
  size: number,
  sectionProperties: SectionProperties,
  speed: number,
  srvMembershipKey: string,
  srvMemberId: string,
  srvMemberType: MemberType,
  srvLicenseOwnershipKey: string,
  srvLicenseValidUntil: string,
  ssn: string,
  startDate: string,
  startTime: string,
  state: number,
  street: string,
  subjectKey: string,
  subjectName: string,
  subjectName2: string,
  subjectType: ModelType,
  subjectCategory: number,
  subTitle: string,
  subType: number,
  tags: string,
  taskState: number,
  taxId: string,
  title: string,
  toastLength: number,
  thumbUrl: string,
  type: number,
  url: string,
  urgency: number,
  userLanguage: string,
  useTouchId: boolean,
  useFaceId: boolean,
  validFrom: string,
  validTo: string,
  version: string,
  watchers: string[],
  weight: number,
  what3words: string,
  youtubeId: string,
  zipCode: string,
}>;